framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: '%env(MAILER_FROM_EMAIL)%'
        headers:
            From: '%env(MAILER_FROM_NAME)% <%env(MAILER_FROM_EMAIL)%>'
            Reply-To: '%env(MAILER_FROM_EMAIL)%'
            X-Mailer: 'wazeBR Mailer'

when@test:
    framework:
        mailer:
            dsn: 'null://null'
