nelmio_security:
    clickjacking:
        paths:
            '^/.*': DENY
    xss_protection:
        enabled: true
        mode_block: true
    content_type:
        nosniff: true
    referrer_policy:
        enabled: true
        policies:
            - no-referrer-when-downgrade
    csp:
        enabled: true
        enforce:
            default-src: ['self']
            script-src: ['self', 'https://cdn.jsdelivr.net']
            style-src: ['self', 'https://cdn.jsdelivr.net', 'https://fonts.googleapis.com']
            img-src: ['self', 'data:', 'https://*.tile.openstreetmap.org']
            font-src: ['self', 'https://fonts.gstatic.com']
            connect-src: ['self', 'https://api.waze.com']
