symfonycasts_reset_password:
    # Disable garbage collection to avoid interface mismatch
    enable_garbage_collection: false
    request_password_repository: App\Repository\ResetPasswordRequestRepository
