symfonycasts_reset_password:
    request_password_repository: App\Repository\ResetPasswordRequestRepository
    lifetime: 3600           # 1 hora
    throttle_limit: 2        # máximo de 2 solicitações por e-mail dentro do intervalo
    # Se quiser desabilitar o throttle, comente ou remova a linha 'throttle_limit'
