<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260902224349 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE cemaden_data (id INT AUTO_INCREMENT NOT NULL, station_code VARCHAR(80) NOT NULL, station_name VARCHAR(120) NOT NULL, municipality VARCHAR(80) NOT NULL, state VARCHAR(2) NOT NULL, latitude NUMERIC(10, 7) NOT NULL, longitude NUMERIC(10, 7) NOT NULL, accumulated_rain NUMERIC(8, 2) DEFAULT NULL, water_level NUMERIC(8, 2) DEFAULT NULL, alert_level VARCHAR(20) DEFAULT NULL, measured_at DATETIME NOT NULL, created_at DATETIME NOT NULL, partner_id INT DEFAULT NULL, INDEX IDX_E3BE8F869393F8FE (partner_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE waze_tvt_route_definition (id INT AUTO_INCREMENT NOT NULL, route_id VARCHAR(255) NOT NULL, name VARCHAR(255) DEFAULT NULL, bbox LONGTEXT DEFAULT NULL, line LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_9C0ACC6434ECB4E6 (route_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE waze_tvt_route_execution (id INT AUTO_INCREMENT NOT NULL, timestamp DATETIME NOT NULL, duration INT DEFAULT NULL, length INT DEFAULT NULL, irregularities INT DEFAULT 0 NOT NULL, traffic_jams INT DEFAULT 0 NOT NULL, avg_speed DOUBLE PRECISION DEFAULT NULL, coords LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, route_definition_id INT NOT NULL, INDEX IDX_ECF63A2C82C7B461 (route_definition_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE waze_tvt_route_execution_coord (id INT AUTO_INCREMENT NOT NULL, position INT NOT NULL, lat DOUBLE PRECISION NOT NULL, lng DOUBLE PRECISION NOT NULL, speed DOUBLE PRECISION DEFAULT NULL, level INT DEFAULT NULL, execution_id INT NOT NULL, INDEX IDX_7D9AC6B457125544 (execution_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('ALTER TABLE cemaden_data ADD CONSTRAINT FK_E3BE8F869393F8FE FOREIGN KEY (partner_id) REFERENCES partners (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE waze_tvt_route_execution ADD CONSTRAINT FK_ECF63A2C82C7B461 FOREIGN KEY (route_definition_id) REFERENCES waze_tvt_route_definition (id)');
        $this->addSql('ALTER TABLE waze_tvt_route_execution_coord ADD CONSTRAINT FK_7D9AC6B457125544 FOREIGN KEY (execution_id) REFERENCES waze_tvt_route_execution (id)');
        $this->addSql('ALTER TABLE activity_log CHANGE action action VARCHAR(60) NOT NULL, CHANGE description description VARCHAR(255) DEFAULT NULL, CHANGE context context JSON DEFAULT NULL, CHANGE ip_address ip_address VARCHAR(45) DEFAULT NULL');
        $this->addSql('ALTER TABLE cemaden_hydro_data CHANGE station_code station_code VARCHAR(30) NOT NULL, CHANGE station_name station_name VARCHAR(120) NOT NULL, CHANGE municipality municipality VARCHAR(120) NOT NULL, CHANGE state state VARCHAR(2) NOT NULL, CHANGE water_level water_level NUMERIC(8, 3) DEFAULT NULL, CHANGE offset_value offset_value NUMERIC(8, 3) DEFAULT NULL, CHANGE qualificacao qualificacao VARCHAR(10) DEFAULT NULL, CHANGE cota_atencao cota_atencao NUMERIC(6, 2) DEFAULT NULL, CHANGE cota_alerta cota_alerta NUMERIC(6, 2) DEFAULT NULL, CHANGE cota_transbordamento cota_transbordamento NUMERIC(6, 2) DEFAULT NULL, CHANGE alert_level alert_level VARCHAR(20) DEFAULT NULL');
        $this->addSql('ALTER TABLE cemaden_stations CHANGE cod_estacao cod_estacao VARCHAR(30) NOT NULL, CHANGE nome nome VARCHAR(120) NOT NULL, CHANGE municipio municipio VARCHAR(120) NOT NULL, CHANGE uf uf VARCHAR(2) NOT NULL, CHANGE lat lat NUMERIC(10, 7) DEFAULT NULL, CHANGE lng lng NUMERIC(10, 7) DEFAULT NULL, CHANGE station_type station_type VARCHAR(20) NOT NULL, CHANGE hydro_url hydro_url LONGTEXT DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE cifs_event CHANGE external_id external_id VARCHAR(64) NOT NULL, CHANGE type type VARCHAR(30) NOT NULL, CHANGE subtype subtype VARCHAR(80) DEFAULT NULL, CHANGE polyline polyline LONGTEXT NOT NULL, CHANGE street street VARCHAR(150) NOT NULL, CHANGE direction direction VARCHAR(20) DEFAULT NULL, CHANGE description description VARCHAR(40) DEFAULT NULL, CHANGE end_time end_time DATETIME DEFAULT NULL, CHANGE update_time update_time DATETIME DEFAULT NULL, CHANGE schedule schedule JSON DEFAULT NULL, CHANGE lane_impact_roadside lane_impact_roadside VARCHAR(10) DEFAULT NULL');
        $this->addSql('ALTER TABLE cifs_event_type CHANGE type type VARCHAR(60) NOT NULL, CHANGE subtype subtype VARCHAR(80) DEFAULT NULL, CHANGE locale locale VARCHAR(5) NOT NULL, CHANGE label label VARCHAR(120) NOT NULL, CHANGE description description LONGTEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE monitored_cities CHANGE name name VARCHAR(80) NOT NULL, CHANGE state state VARCHAR(2) NOT NULL');
        $this->addSql('ALTER TABLE monitored_links CHANGE url url VARCHAR(500) NOT NULL, CHANGE label label VARCHAR(120) DEFAULT NULL, CHANGE link_type link_type VARCHAR(20) DEFAULT \'waze_feed\' NOT NULL, CHANGE last_collected_at last_collected_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE notifications CHANGE type type VARCHAR(40) NOT NULL, CHANGE title title VARCHAR(180) NOT NULL, CHANGE body body LONGTEXT NOT NULL, CHANGE reference_id reference_id VARCHAR(120) DEFAULT NULL');
        $this->addSql('ALTER TABLE partners CHANGE slug slug VARCHAR(80) NOT NULL, CHANGE name name VARCHAR(120) NOT NULL, CHANGE email email VARCHAR(180) NOT NULL, CHANGE api_token api_token VARCHAR(64) NOT NULL, CHANGE bbox bbox VARCHAR(100) DEFAULT NULL, CHANGE cemaden_states cemaden_states LONGTEXT NOT NULL');
        $this->addSql('ALTER TABLE reset_password_request CHANGE selector selector VARCHAR(20) NOT NULL, CHANGE hashed_token hashed_token VARCHAR(100) NOT NULL');
        $this->addSql('ALTER TABLE users CHANGE email email VARCHAR(180) NOT NULL, CHANGE name name VARCHAR(255) NOT NULL, CHANGE roles roles JSON NOT NULL, CHANGE password password VARCHAR(255) NOT NULL, CHANGE reset_token reset_token VARCHAR(255) DEFAULT NULL, CHANGE reset_token_expires_at reset_token_expires_at DATETIME DEFAULT NULL, CHANGE last_login_at last_login_at DATETIME DEFAULT NULL, CHANGE last_login_ip last_login_ip VARCHAR(45) DEFAULT NULL, CHANGE field_agent_permissions field_agent_permissions JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE waze_alert_type CHANGE subtype subtype VARCHAR(80) DEFAULT NULL');
        $this->addSql('ALTER TABLE waze_alerts CHANGE waze_id waze_id VARCHAR(80) NOT NULL, CHANGE type type VARCHAR(60) NOT NULL, CHANGE subtype subtype VARCHAR(60) DEFAULT NULL, CHANGE street street VARCHAR(120) DEFAULT NULL, CHANGE city city VARCHAR(80) DEFAULT NULL, CHANGE country country VARCHAR(10) DEFAULT NULL, CHANGE report_description report_description LONGTEXT DEFAULT NULL, CHANGE additional_info additional_info LONGTEXT DEFAULT NULL, CHANGE comments comments JSON NOT NULL, CHANGE jam_uuid jam_uuid VARCHAR(80) DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE waze_counts CHANGE wazers_level0 wazers_level0 NUMERIC(10, 1) DEFAULT NULL, CHANGE wazers_level1 wazers_level1 NUMERIC(10, 1) DEFAULT NULL, CHANGE wazers_level2 wazers_level2 NUMERIC(10, 1) DEFAULT NULL, CHANGE wazers_level3 wazers_level3 NUMERIC(10, 1) DEFAULT NULL, CHANGE wazers_level4 wazers_level4 NUMERIC(10, 1) DEFAULT NULL, CHANGE wazers_total wazers_total NUMERIC(10, 1) DEFAULT NULL, CHANGE raw_data raw_data JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE waze_irregularities CHANGE waze_id waze_id VARCHAR(64) DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL, CHANGE from_name from_name VARCHAR(255) DEFAULT NULL, CHANGE to_name to_name VARCHAR(255) DEFAULT NULL, CHANGE avg_speed avg_speed DOUBLE PRECISION DEFAULT NULL, CHANGE historic_speed historic_speed DOUBLE PRECISION DEFAULT NULL, CHANGE bbox bbox JSON DEFAULT NULL, CHANGE line line JSON DEFAULT NULL, CHANGE collected_at collected_at DATETIME DEFAULT NULL, CHANGE lead_alert_id lead_alert_id VARCHAR(64) DEFAULT NULL, CHANGE lead_alert_type lead_alert_type VARCHAR(64) DEFAULT NULL, CHANGE lead_alert_sub_type lead_alert_sub_type VARCHAR(64) DEFAULT NULL, CHANGE lead_alert_position lead_alert_position JSON DEFAULT NULL, CHANGE lead_alert_city lead_alert_city VARCHAR(255) DEFAULT NULL, CHANGE lead_alert_external_image_id lead_alert_external_image_id VARCHAR(255) DEFAULT NULL, CHANGE lead_alert_street lead_alert_street VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE waze_route_links CHANGE name name VARCHAR(80) NOT NULL, CHANGE coordinates coordinates JSON NOT NULL');
        $this->addSql('ALTER TABLE waze_route_snapshots CHANGE avg_speed avg_speed DOUBLE PRECISION DEFAULT NULL, CHANGE historic_speed historic_speed DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE waze_routes CHANGE waze_id waze_id VARCHAR(50) DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL, CHANGE from_name from_name VARCHAR(255) DEFAULT NULL, CHANGE to_name to_name VARCHAR(255) DEFAULT NULL, CHANGE type type VARCHAR(30) DEFAULT NULL, CHANGE line line JSON DEFAULT NULL, CHANGE bbox bbox JSON DEFAULT NULL, CHANGE alternate_route alternate_route JSON DEFAULT NULL, CHANGE description description VARCHAR(1000) DEFAULT NULL, CHANGE coordinates coordinates JSON DEFAULT NULL, CHANGE collected_at collected_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE waze_traffic_jams CHANGE waze_id waze_id VARCHAR(80) NOT NULL, CHANGE street street VARCHAR(120) DEFAULT NULL, CHANGE city city VARCHAR(80) DEFAULT NULL, CHANGE country country VARCHAR(10) DEFAULT NULL, CHANGE speed_kmh speed_kmh NUMERIC(8, 2) DEFAULT NULL, CHANGE speed speed NUMERIC(8, 3) DEFAULT NULL, CHANGE type type VARCHAR(40) DEFAULT NULL, CHANGE turn_type turn_type VARCHAR(40) DEFAULT NULL, CHANGE start_node start_node VARCHAR(200) DEFAULT NULL, CHANGE end_node end_node VARCHAR(200) DEFAULT NULL, CHANGE caused_by caused_by VARCHAR(80) DEFAULT NULL, CHANGE line line JSON NOT NULL, CHANGE segments segments JSON NOT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE waze_tvt_route_history CHANGE speed_kmh speed_kmh NUMERIC(5, 2) DEFAULT NULL, CHANGE collected_at collected_at DATETIME DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE waze_tvt_route_history_coords CHANGE latitude latitude NUMERIC(10, 8) DEFAULT NULL, CHANGE longitude longitude NUMERIC(11, 8) DEFAULT NULL');
        $this->addSql('ALTER TABLE waze_tvt_routes CHANGE waze_route_id waze_route_id VARCHAR(40) DEFAULT NULL, CHANGE parent_waze_id parent_waze_id VARCHAR(40) DEFAULT NULL, CHANGE name name VARCHAR(160) DEFAULT NULL, CHANGE type type VARCHAR(20) DEFAULT NULL, CHANGE from_name from_name VARCHAR(200) DEFAULT NULL, CHANGE to_name to_name VARCHAR(200) DEFAULT NULL, CHANGE line line JSON NOT NULL, CHANGE bbox bbox JSON DEFAULT NULL, CHANGE sub_routes_raw sub_routes_raw JSON NOT NULL');
        $this->addSql('ALTER TABLE waze_tvt_snapshots CHANGE feed_name feed_name VARCHAR(120) DEFAULT NULL, CHANGE area_name area_name VARCHAR(120) DEFAULT NULL, CHANGE broadcaster_id broadcaster_id VARCHAR(80) DEFAULT NULL, CHANGE bbox bbox JSON DEFAULT NULL, CHANGE users_on_jams users_on_jams JSON NOT NULL, CHANGE length_of_jams length_of_jams JSON NOT NULL, CHANGE irregularities irregularities JSON NOT NULL');
        $this->addSql('ALTER TABLE wazesubroutes CHANGE from_name from_name VARCHAR(255) DEFAULT NULL, CHANGE to_name to_name VARCHAR(255) DEFAULT NULL, CHANGE avg_speed avg_speed DOUBLE PRECISION DEFAULT NULL, CHANGE historic_speed historic_speed DOUBLE PRECISION DEFAULT NULL, CHANGE line line JSON DEFAULT NULL, CHANGE bbox bbox JSON DEFAULT NULL, CHANGE lead_alert_id lead_alert_id VARCHAR(64) DEFAULT NULL, CHANGE lead_alert_type lead_alert_type VARCHAR(64) DEFAULT NULL, CHANGE lead_alert_sub_type lead_alert_sub_type VARCHAR(64) DEFAULT NULL, CHANGE lead_alert_position lead_alert_position JSON DEFAULT NULL, CHANGE lead_alert_street lead_alert_street VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE wme_update_request CHANGE external_id external_id VARCHAR(64) NOT NULL, CHANGE type type VARCHAR(100) DEFAULT NULL, CHANGE status status VARCHAR(32) NOT NULL, CHANGE description description LONGTEXT DEFAULT NULL, CHANGE severity severity VARCHAR(32) DEFAULT NULL, CHANGE source source VARCHAR(64) DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE cemaden_data DROP FOREIGN KEY FK_E3BE8F869393F8FE');
        $this->addSql('ALTER TABLE waze_tvt_route_execution DROP FOREIGN KEY FK_ECF63A2C82C7B461');
        $this->addSql('ALTER TABLE waze_tvt_route_execution_coord DROP FOREIGN KEY FK_7D9AC6B457125544');
        $this->addSql('DROP TABLE cemaden_data');
        $this->addSql('DROP TABLE waze_tvt_route_definition');
        $this->addSql('DROP TABLE waze_tvt_route_execution');
        $this->addSql('DROP TABLE waze_tvt_route_execution_coord');
        $this->addSql('ALTER TABLE activity_log CHANGE action action VARCHAR(60) NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE description description VARCHAR(255) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE context context LONGTEXT DEFAULT NULL COLLATE `utf8mb4_bin`, CHANGE ip_address ip_address VARCHAR(45) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`');
        $this->addSql('ALTER TABLE cemaden_hydro_data CHANGE station_code station_code VARCHAR(30) NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE station_name station_name VARCHAR(120) NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE municipality municipality VARCHAR(120) NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE state state VARCHAR(2) NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE water_level water_level NUMERIC(8, 3) DEFAULT \'NULL\', CHANGE offset_value offset_value NUMERIC(8, 3) DEFAULT \'NULL\', CHANGE qualificacao qualificacao VARCHAR(10) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE cota_atencao cota_atencao NUMERIC(6, 2) DEFAULT \'NULL\', CHANGE cota_alerta cota_alerta NUMERIC(6, 2) DEFAULT \'NULL\', CHANGE cota_transbordamento cota_transbordamento NUMERIC(6, 2) DEFAULT \'NULL\', CHANGE alert_level alert_level VARCHAR(20) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`');
        $this->addSql('ALTER TABLE cemaden_stations CHANGE cod_estacao cod_estacao VARCHAR(30) NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE nome nome VARCHAR(120) NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE municipio municipio VARCHAR(120) NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE uf uf VARCHAR(2) NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE lat lat NUMERIC(10, 7) DEFAULT \'NULL\', CHANGE lng lng NUMERIC(10, 7) DEFAULT \'NULL\', CHANGE station_type station_type VARCHAR(20) NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE hydro_url hydro_url LONGTEXT DEFAULT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE cifs_event CHANGE external_id external_id VARCHAR(64) NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE type type VARCHAR(30) NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE subtype subtype VARCHAR(80) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE polyline polyline LONGTEXT NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE street street VARCHAR(150) NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE direction direction VARCHAR(20) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE description description VARCHAR(40) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE end_time end_time DATETIME DEFAULT \'NULL\', CHANGE update_time update_time DATETIME DEFAULT \'NULL\', CHANGE schedule schedule LONGTEXT DEFAULT NULL COLLATE `utf8mb4_bin`, CHANGE lane_impact_roadside lane_impact_roadside VARCHAR(10) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`');
        $this->addSql('ALTER TABLE cifs_event_type CHANGE type type VARCHAR(60) NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE subtype subtype VARCHAR(80) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE locale locale VARCHAR(5) NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE label label VARCHAR(120) NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE description description LONGTEXT DEFAULT NULL COLLATE `utf8mb4_uca1400_ai_ci`');
        $this->addSql('ALTER TABLE monitored_cities CHANGE name name VARCHAR(80) NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE state state VARCHAR(2) NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`');
        $this->addSql('ALTER TABLE monitored_links CHANGE url url VARCHAR(500) NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE label label VARCHAR(120) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE link_type link_type VARCHAR(20) DEFAULT \'\'\'waze_feed\'\'\' NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE last_collected_at last_collected_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE notifications CHANGE type type VARCHAR(40) NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE title title VARCHAR(180) NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE body body LONGTEXT NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE reference_id reference_id VARCHAR(120) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`');
        $this->addSql('ALTER TABLE partners CHANGE slug slug VARCHAR(80) NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE name name VARCHAR(120) NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE email email VARCHAR(180) NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE api_token api_token VARCHAR(64) NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE bbox bbox VARCHAR(100) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE cemaden_states cemaden_states LONGTEXT NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`');
        $this->addSql('ALTER TABLE reset_password_request CHANGE selector selector VARCHAR(20) NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE hashed_token hashed_token VARCHAR(100) NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`');
        $this->addSql('ALTER TABLE users CHANGE email email VARCHAR(180) NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE roles roles LONGTEXT NOT NULL COLLATE `utf8mb4_bin`, CHANGE password password VARCHAR(255) NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE name name VARCHAR(255) NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE reset_token reset_token VARCHAR(255) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE reset_token_expires_at reset_token_expires_at DATETIME DEFAULT \'NULL\', CHANGE last_login_at last_login_at DATETIME DEFAULT \'NULL\', CHANGE last_login_ip last_login_ip VARCHAR(45) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE field_agent_permissions field_agent_permissions LONGTEXT DEFAULT NULL COLLATE `utf8mb4_bin`');
        $this->addSql('ALTER TABLE wazesubroutes CHANGE from_name from_name VARCHAR(255) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE to_name to_name VARCHAR(255) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE avg_speed avg_speed DOUBLE PRECISION DEFAULT \'NULL\', CHANGE historic_speed historic_speed DOUBLE PRECISION DEFAULT \'NULL\', CHANGE line line LONGTEXT DEFAULT NULL COLLATE `utf8mb4_bin`, CHANGE bbox bbox LONGTEXT DEFAULT NULL COLLATE `utf8mb4_bin`, CHANGE lead_alert_id lead_alert_id VARCHAR(64) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE lead_alert_type lead_alert_type VARCHAR(64) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE lead_alert_sub_type lead_alert_sub_type VARCHAR(64) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE lead_alert_position lead_alert_position LONGTEXT DEFAULT NULL COLLATE `utf8mb4_bin`, CHANGE lead_alert_street lead_alert_street VARCHAR(255) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`');
        $this->addSql('ALTER TABLE waze_alerts CHANGE waze_id waze_id VARCHAR(80) NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE type type VARCHAR(60) NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE subtype subtype VARCHAR(60) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE street street VARCHAR(120) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE city city VARCHAR(80) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE country country VARCHAR(10) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE report_description report_description LONGTEXT DEFAULT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE additional_info additional_info LONGTEXT DEFAULT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE comments comments LONGTEXT NOT NULL COLLATE `utf8mb4_bin`, CHANGE jam_uuid jam_uuid VARCHAR(80) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE waze_alert_type CHANGE subtype subtype VARCHAR(80) DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE waze_counts CHANGE wazers_level0 wazers_level0 NUMERIC(10, 1) DEFAULT \'NULL\', CHANGE wazers_level1 wazers_level1 NUMERIC(10, 1) DEFAULT \'NULL\', CHANGE wazers_level2 wazers_level2 NUMERIC(10, 1) DEFAULT \'NULL\', CHANGE wazers_level3 wazers_level3 NUMERIC(10, 1) DEFAULT \'NULL\', CHANGE wazers_level4 wazers_level4 NUMERIC(10, 1) DEFAULT \'NULL\', CHANGE wazers_total wazers_total NUMERIC(10, 1) DEFAULT \'NULL\', CHANGE raw_data raw_data LONGTEXT DEFAULT NULL COLLATE `utf8mb4_bin`');
        $this->addSql('ALTER TABLE waze_irregularities CHANGE waze_id waze_id VARCHAR(64) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE name name VARCHAR(255) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE from_name from_name VARCHAR(255) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE to_name to_name VARCHAR(255) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE avg_speed avg_speed DOUBLE PRECISION DEFAULT \'NULL\', CHANGE historic_speed historic_speed DOUBLE PRECISION DEFAULT \'NULL\', CHANGE bbox bbox LONGTEXT DEFAULT NULL COLLATE `utf8mb4_bin`, CHANGE line line LONGTEXT DEFAULT NULL COLLATE `utf8mb4_bin`, CHANGE collected_at collected_at DATETIME DEFAULT \'NULL\', CHANGE lead_alert_id lead_alert_id VARCHAR(64) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE lead_alert_type lead_alert_type VARCHAR(64) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE lead_alert_sub_type lead_alert_sub_type VARCHAR(64) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE lead_alert_position lead_alert_position LONGTEXT DEFAULT NULL COLLATE `utf8mb4_bin`, CHANGE lead_alert_city lead_alert_city VARCHAR(255) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE lead_alert_external_image_id lead_alert_external_image_id VARCHAR(255) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE lead_alert_street lead_alert_street VARCHAR(255) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`');
        $this->addSql('ALTER TABLE waze_routes CHANGE waze_id waze_id VARCHAR(50) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE name name VARCHAR(255) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE from_name from_name VARCHAR(255) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE to_name to_name VARCHAR(255) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE type type VARCHAR(30) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE line line LONGTEXT DEFAULT NULL COLLATE `utf8mb4_bin`, CHANGE bbox bbox LONGTEXT DEFAULT NULL COLLATE `utf8mb4_bin`, CHANGE alternate_route alternate_route LONGTEXT DEFAULT NULL COLLATE `utf8mb4_bin`, CHANGE description description VARCHAR(1000) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE coordinates coordinates LONGTEXT DEFAULT NULL COLLATE `utf8mb4_bin`, CHANGE collected_at collected_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE waze_route_links CHANGE name name VARCHAR(80) NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE coordinates coordinates LONGTEXT NOT NULL COLLATE `utf8mb4_bin`');
        $this->addSql('ALTER TABLE waze_route_snapshots CHANGE avg_speed avg_speed DOUBLE PRECISION DEFAULT \'NULL\', CHANGE historic_speed historic_speed DOUBLE PRECISION DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE waze_traffic_jams CHANGE waze_id waze_id VARCHAR(80) NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE street street VARCHAR(120) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE city city VARCHAR(80) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE country country VARCHAR(10) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE speed_kmh speed_kmh NUMERIC(8, 2) DEFAULT \'NULL\', CHANGE speed speed NUMERIC(8, 3) DEFAULT \'NULL\', CHANGE type type VARCHAR(40) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE turn_type turn_type VARCHAR(40) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE start_node start_node VARCHAR(200) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE end_node end_node VARCHAR(200) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE caused_by caused_by VARCHAR(80) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE line line LONGTEXT NOT NULL COLLATE `utf8mb4_bin`, CHANGE segments segments LONGTEXT NOT NULL COLLATE `utf8mb4_bin`, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE waze_tvt_routes CHANGE waze_route_id waze_route_id VARCHAR(40) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE parent_waze_id parent_waze_id VARCHAR(40) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE name name VARCHAR(160) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE type type VARCHAR(20) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE from_name from_name VARCHAR(200) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE to_name to_name VARCHAR(200) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE line line LONGTEXT NOT NULL COLLATE `utf8mb4_bin`, CHANGE bbox bbox LONGTEXT DEFAULT NULL COLLATE `utf8mb4_bin`, CHANGE sub_routes_raw sub_routes_raw LONGTEXT NOT NULL COLLATE `utf8mb4_bin`');
        $this->addSql('ALTER TABLE waze_tvt_route_history CHANGE speed_kmh speed_kmh NUMERIC(5, 2) DEFAULT \'NULL\', CHANGE collected_at collected_at DATETIME DEFAULT \'NULL\', CHANGE created_at created_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE waze_tvt_route_history_coords CHANGE latitude latitude NUMERIC(10, 8) DEFAULT \'NULL\', CHANGE longitude longitude NUMERIC(11, 8) DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE waze_tvt_snapshots CHANGE feed_name feed_name VARCHAR(120) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE area_name area_name VARCHAR(120) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE broadcaster_id broadcaster_id VARCHAR(80) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE bbox bbox LONGTEXT DEFAULT NULL COLLATE `utf8mb4_bin`, CHANGE users_on_jams users_on_jams LONGTEXT NOT NULL COLLATE `utf8mb4_bin`, CHANGE length_of_jams length_of_jams LONGTEXT NOT NULL COLLATE `utf8mb4_bin`, CHANGE irregularities irregularities LONGTEXT NOT NULL COLLATE `utf8mb4_bin`');
        $this->addSql('ALTER TABLE wme_update_request CHANGE external_id external_id VARCHAR(64) NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE type type VARCHAR(100) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE status status VARCHAR(32) NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE description description LONGTEXT DEFAULT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE severity severity VARCHAR(32) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE source source VARCHAR(64) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`');
    }
}
