<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Cria waze_alert_type: tradução pt/en/es dos tipos e subtipos do feed de
 * LEITURA do Waze (WazeAlert / Traffic View), conforme a tabela oficial
 * https://support.google.com/waze/partners/answer/13658466
 *
 * Mesmo padrão do cifs_event_type, mas para a taxonomia de leitura, que é
 * diferente da spec CIFS de envio (inclui WEATHERHAZARD, MISC, CONSTRUCTION
 * e o valor NO_SUBTYPE, que não existem no lado de envio).
 */
final class Version20260720_create_waze_alert_type extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Cria a tabela waze_alert_type com as traduções pt/en/es dos tipos/subtipos do feed de leitura do Waze.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE waze_alert_type (
            id INT AUTO_INCREMENT NOT NULL,
            type VARCHAR(60) NOT NULL,
            subtype VARCHAR(80) DEFAULT NULL,
            locale VARCHAR(5) NOT NULL,
            label VARCHAR(120) NOT NULL,
            UNIQUE INDEX uniq_walert_type_subtype_locale (type, subtype, locale),
            PRIMARY KEY(id)
        ) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');

        $this->addSql(<<<'SQL'
INSERT INTO waze_alert_type (type, subtype, locale, label) VALUES
    ('ACCIDENT', NULL, 'pt', 'Acidente'),
    ('ACCIDENT', NULL, 'en', 'Accident'),
    ('ACCIDENT', NULL, 'es', 'Accidente'),
    ('ACCIDENT', 'ACCIDENT_MINOR', 'pt', 'Acidente leve'),
    ('ACCIDENT', 'ACCIDENT_MINOR', 'en', 'Minor accident'),
    ('ACCIDENT', 'ACCIDENT_MINOR', 'es', 'Accidente leve'),
    ('ACCIDENT', 'ACCIDENT_MAJOR', 'pt', 'Acidente grave'),
    ('ACCIDENT', 'ACCIDENT_MAJOR', 'en', 'Major accident'),
    ('ACCIDENT', 'ACCIDENT_MAJOR', 'es', 'Accidente grave'),
    ('ACCIDENT', 'NO_SUBTYPE', 'pt', 'Sem subtipo específico'),
    ('ACCIDENT', 'NO_SUBTYPE', 'en', 'No specific subtype'),
    ('ACCIDENT', 'NO_SUBTYPE', 'es', 'Sin subtipo específico'),
    ('JAM', NULL, 'pt', 'Congestionamento'),
    ('JAM', NULL, 'en', 'Jam'),
    ('JAM', NULL, 'es', 'Congestión'),
    ('JAM', 'JAM_LIGHT_TRAFFIC', 'pt', 'Trânsito leve'),
    ('JAM', 'JAM_LIGHT_TRAFFIC', 'en', 'Light traffic'),
    ('JAM', 'JAM_LIGHT_TRAFFIC', 'es', 'Tráfico ligero'),
    ('JAM', 'JAM_MODERATE_TRAFFIC', 'pt', 'Trânsito moderado'),
    ('JAM', 'JAM_MODERATE_TRAFFIC', 'en', 'Moderate traffic'),
    ('JAM', 'JAM_MODERATE_TRAFFIC', 'es', 'Tráfico moderado'),
    ('JAM', 'JAM_HEAVY_TRAFFIC', 'pt', 'Trânsito intenso'),
    ('JAM', 'JAM_HEAVY_TRAFFIC', 'en', 'Heavy traffic'),
    ('JAM', 'JAM_HEAVY_TRAFFIC', 'es', 'Tráfico intenso'),
    ('JAM', 'JAM_STAND_STILL_TRAFFIC', 'pt', 'Trânsito parado'),
    ('JAM', 'JAM_STAND_STILL_TRAFFIC', 'en', 'Stand-still traffic'),
    ('JAM', 'JAM_STAND_STILL_TRAFFIC', 'es', 'Tráfico detenido'),
    ('JAM', 'NO_SUBTYPE', 'pt', 'Sem subtipo específico'),
    ('JAM', 'NO_SUBTYPE', 'en', 'No specific subtype'),
    ('JAM', 'NO_SUBTYPE', 'es', 'Sin subtipo específico'),
    ('MISC', NULL, 'pt', 'Diversos'),
    ('MISC', NULL, 'en', 'Miscellaneous'),
    ('MISC', NULL, 'es', 'Varios'),
    ('MISC', 'NO_SUBTYPE', 'pt', 'Sem subtipo específico'),
    ('MISC', 'NO_SUBTYPE', 'en', 'No specific subtype'),
    ('MISC', 'NO_SUBTYPE', 'es', 'Sin subtipo específico'),
    ('CONSTRUCTION', NULL, 'pt', 'Obra'),
    ('CONSTRUCTION', NULL, 'en', 'Construction'),
    ('CONSTRUCTION', NULL, 'es', 'Obras'),
    ('CONSTRUCTION', 'NO_SUBTYPE', 'pt', 'Sem subtipo específico'),
    ('CONSTRUCTION', 'NO_SUBTYPE', 'en', 'No specific subtype'),
    ('CONSTRUCTION', 'NO_SUBTYPE', 'es', 'Sin subtipo específico'),
    ('ROAD_CLOSED', NULL, 'pt', 'Via Interditada'),
    ('ROAD_CLOSED', NULL, 'en', 'Road Closed'),
    ('ROAD_CLOSED', NULL, 'es', 'Vía Cerrada'),
    ('ROAD_CLOSED', 'ROAD_CLOSED_HAZARD', 'pt', 'Interditada por perigo'),
    ('ROAD_CLOSED', 'ROAD_CLOSED_HAZARD', 'en', 'Closed due to hazard'),
    ('ROAD_CLOSED', 'ROAD_CLOSED_HAZARD', 'es', 'Cerrada por peligro'),
    ('ROAD_CLOSED', 'ROAD_CLOSED_CONSTRUCTION', 'pt', 'Interditada por obra'),
    ('ROAD_CLOSED', 'ROAD_CLOSED_CONSTRUCTION', 'en', 'Closed for construction'),
    ('ROAD_CLOSED', 'ROAD_CLOSED_CONSTRUCTION', 'es', 'Cerrada por obras'),
    ('ROAD_CLOSED', 'ROAD_CLOSED_EVENT', 'pt', 'Interditada por evento'),
    ('ROAD_CLOSED', 'ROAD_CLOSED_EVENT', 'en', 'Closed for event'),
    ('ROAD_CLOSED', 'ROAD_CLOSED_EVENT', 'es', 'Cerrada por evento'),
    ('ROAD_CLOSED', 'NO_SUBTYPE', 'pt', 'Sem subtipo específico'),
    ('ROAD_CLOSED', 'NO_SUBTYPE', 'en', 'No specific subtype'),
    ('ROAD_CLOSED', 'NO_SUBTYPE', 'es', 'Sin subtipo específico'),
    ('HAZARD', NULL, 'pt', 'Perigo'),
    ('HAZARD', NULL, 'en', 'Hazard'),
    ('HAZARD', NULL, 'es', 'Peligro'),
    ('HAZARD', 'HAZARD_ON_ROAD', 'pt', 'Perigo na via'),
    ('HAZARD', 'HAZARD_ON_ROAD', 'en', 'Hazard on road'),
    ('HAZARD', 'HAZARD_ON_ROAD', 'es', 'Peligro en la vía'),
    ('HAZARD', 'HAZARD_ON_ROAD_CAR_STOPPED', 'pt', 'Veículo parado na via'),
    ('HAZARD', 'HAZARD_ON_ROAD_CAR_STOPPED', 'en', 'Car stopped on road'),
    ('HAZARD', 'HAZARD_ON_ROAD_CAR_STOPPED', 'es', 'Vehículo detenido en la vía'),
    ('HAZARD', 'HAZARD_ON_ROAD_CONSTRUCTION', 'pt', 'Obra na via'),
    ('HAZARD', 'HAZARD_ON_ROAD_CONSTRUCTION', 'en', 'Construction on road'),
    ('HAZARD', 'HAZARD_ON_ROAD_CONSTRUCTION', 'es', 'Obras en la vía'),
    ('HAZARD', 'HAZARD_ON_ROAD_ICE', 'pt', 'Gelo na pista'),
    ('HAZARD', 'HAZARD_ON_ROAD_ICE', 'en', 'Ice on road'),
    ('HAZARD', 'HAZARD_ON_ROAD_ICE', 'es', 'Hielo en la vía'),
    ('HAZARD', 'HAZARD_ON_ROAD_LANE_CLOSED', 'pt', 'Faixa fechada'),
    ('HAZARD', 'HAZARD_ON_ROAD_LANE_CLOSED', 'en', 'Lane closed'),
    ('HAZARD', 'HAZARD_ON_ROAD_LANE_CLOSED', 'es', 'Carril cerrado'),
    ('HAZARD', 'HAZARD_ON_ROAD_OBJECT', 'pt', 'Objeto na pista'),
    ('HAZARD', 'HAZARD_ON_ROAD_OBJECT', 'en', 'Object on road'),
    ('HAZARD', 'HAZARD_ON_ROAD_OBJECT', 'es', 'Objeto en la vía'),
    ('HAZARD', 'HAZARD_ON_ROAD_OIL', 'pt', 'Óleo na pista'),
    ('HAZARD', 'HAZARD_ON_ROAD_OIL', 'en', 'Oil on road'),
    ('HAZARD', 'HAZARD_ON_ROAD_OIL', 'es', 'Aceite en la vía'),
    ('HAZARD', 'HAZARD_ON_ROAD_POT_HOLE', 'pt', 'Buraco na pista'),
    ('HAZARD', 'HAZARD_ON_ROAD_POT_HOLE', 'en', 'Pot hole'),
    ('HAZARD', 'HAZARD_ON_ROAD_POT_HOLE', 'es', 'Bache en la vía'),
    ('HAZARD', 'HAZARD_ON_ROAD_ROAD_KILL', 'pt', 'Animal morto na pista'),
    ('HAZARD', 'HAZARD_ON_ROAD_ROAD_KILL', 'en', 'Road kill'),
    ('HAZARD', 'HAZARD_ON_ROAD_ROAD_KILL', 'es', 'Animal atropellado en la vía'),
    ('HAZARD', 'HAZARD_ON_ROAD_TRAFFIC_LIGHT_FAULT', 'pt', 'Semáforo com defeito'),
    ('HAZARD', 'HAZARD_ON_ROAD_TRAFFIC_LIGHT_FAULT', 'en', 'Traffic light fault'),
    ('HAZARD', 'HAZARD_ON_ROAD_TRAFFIC_LIGHT_FAULT', 'es', 'Semáforo averiado'),
    ('HAZARD', 'HAZARD_ON_SHOULDER', 'pt', 'Perigo no acostamento'),
    ('HAZARD', 'HAZARD_ON_SHOULDER', 'en', 'Hazard on shoulder'),
    ('HAZARD', 'HAZARD_ON_SHOULDER', 'es', 'Peligro en el acotamiento'),
    ('HAZARD', 'HAZARD_ON_SHOULDER_ANIMALS', 'pt', 'Animais no acostamento'),
    ('HAZARD', 'HAZARD_ON_SHOULDER_ANIMALS', 'en', 'Animals on shoulder'),
    ('HAZARD', 'HAZARD_ON_SHOULDER_ANIMALS', 'es', 'Animales en el acotamiento'),
    ('HAZARD', 'HAZARD_ON_SHOULDER_CAR_STOPPED', 'pt', 'Veículo parado no acostamento'),
    ('HAZARD', 'HAZARD_ON_SHOULDER_CAR_STOPPED', 'en', 'Car stopped on shoulder'),
    ('HAZARD', 'HAZARD_ON_SHOULDER_CAR_STOPPED', 'es', 'Vehículo detenido en el acotamiento'),
    ('HAZARD', 'HAZARD_ON_SHOULDER_MISSING_SIGN', 'pt', 'Placa de sinalização ausente'),
    ('HAZARD', 'HAZARD_ON_SHOULDER_MISSING_SIGN', 'en', 'Missing sign'),
    ('HAZARD', 'HAZARD_ON_SHOULDER_MISSING_SIGN', 'es', 'Señal de tránsito ausente'),
    ('HAZARD', 'HAZARD_WEATHER', 'pt', 'Condição climática'),
    ('HAZARD', 'HAZARD_WEATHER', 'en', 'Weather hazard'),
    ('HAZARD', 'HAZARD_WEATHER', 'es', 'Peligro climático'),
    ('HAZARD', 'HAZARD_WEATHER_FLOOD', 'pt', 'Alagamento'),
    ('HAZARD', 'HAZARD_WEATHER_FLOOD', 'en', 'Flood'),
    ('HAZARD', 'HAZARD_WEATHER_FLOOD', 'es', 'Inundación'),
    ('HAZARD', 'HAZARD_WEATHER_FOG', 'pt', 'Neblina'),
    ('HAZARD', 'HAZARD_WEATHER_FOG', 'en', 'Fog'),
    ('HAZARD', 'HAZARD_WEATHER_FOG', 'es', 'Niebla'),
    ('HAZARD', 'HAZARD_WEATHER_FREEZING_RAIN', 'pt', 'Chuva congelante'),
    ('HAZARD', 'HAZARD_WEATHER_FREEZING_RAIN', 'en', 'Freezing rain'),
    ('HAZARD', 'HAZARD_WEATHER_FREEZING_RAIN', 'es', 'Lluvia helada'),
    ('HAZARD', 'HAZARD_WEATHER_HAIL', 'pt', 'Granizo'),
    ('HAZARD', 'HAZARD_WEATHER_HAIL', 'en', 'Hail'),
    ('HAZARD', 'HAZARD_WEATHER_HAIL', 'es', 'Granizo'),
    ('HAZARD', 'HAZARD_WEATHER_HEAT_WAVE', 'pt', 'Onda de calor'),
    ('HAZARD', 'HAZARD_WEATHER_HEAT_WAVE', 'en', 'Heat wave'),
    ('HAZARD', 'HAZARD_WEATHER_HEAT_WAVE', 'es', 'Ola de calor'),
    ('HAZARD', 'HAZARD_WEATHER_HEAVY_RAIN', 'pt', 'Chuva forte'),
    ('HAZARD', 'HAZARD_WEATHER_HEAVY_RAIN', 'en', 'Heavy rain'),
    ('HAZARD', 'HAZARD_WEATHER_HEAVY_RAIN', 'es', 'Lluvia fuerte'),
    ('HAZARD', 'HAZARD_WEATHER_HEAVY_SNOW', 'pt', 'Neve intensa'),
    ('HAZARD', 'HAZARD_WEATHER_HEAVY_SNOW', 'en', 'Heavy snow'),
    ('HAZARD', 'HAZARD_WEATHER_HEAVY_SNOW', 'es', 'Nieve intensa'),
    ('HAZARD', 'HAZARD_WEATHER_HURRICANE', 'pt', 'Furacão'),
    ('HAZARD', 'HAZARD_WEATHER_HURRICANE', 'en', 'Hurricane'),
    ('HAZARD', 'HAZARD_WEATHER_HURRICANE', 'es', 'Huracán'),
    ('HAZARD', 'HAZARD_WEATHER_MONSOON', 'pt', 'Monção'),
    ('HAZARD', 'HAZARD_WEATHER_MONSOON', 'en', 'Monsoon'),
    ('HAZARD', 'HAZARD_WEATHER_MONSOON', 'es', 'Monzón'),
    ('HAZARD', 'HAZARD_WEATHER_TORNADO', 'pt', 'Tornado'),
    ('HAZARD', 'HAZARD_WEATHER_TORNADO', 'en', 'Tornado'),
    ('HAZARD', 'HAZARD_WEATHER_TORNADO', 'es', 'Tornado'),
    ('HAZARD', 'NO_SUBTYPE', 'pt', 'Sem subtipo específico'),
    ('HAZARD', 'NO_SUBTYPE', 'en', 'No specific subtype'),
    ('HAZARD', 'NO_SUBTYPE', 'es', 'Sin subtipo específico'),
    ('WEATHERHAZARD', NULL, 'pt', 'Perigo climático'),
    ('WEATHERHAZARD', NULL, 'en', 'Weather hazard'),
    ('WEATHERHAZARD', NULL, 'es', 'Peligro climático'),
    ('WEATHERHAZARD', 'HAZARD_ON_ROAD', 'pt', 'Perigo na via'),
    ('WEATHERHAZARD', 'HAZARD_ON_ROAD', 'en', 'Hazard on road'),
    ('WEATHERHAZARD', 'HAZARD_ON_ROAD', 'es', 'Peligro en la vía'),
    ('WEATHERHAZARD', 'HAZARD_ON_ROAD_CAR_STOPPED', 'pt', 'Veículo parado na via'),
    ('WEATHERHAZARD', 'HAZARD_ON_ROAD_CAR_STOPPED', 'en', 'Car stopped on road'),
    ('WEATHERHAZARD', 'HAZARD_ON_ROAD_CAR_STOPPED', 'es', 'Vehículo detenido en la vía'),
    ('WEATHERHAZARD', 'HAZARD_ON_ROAD_CONSTRUCTION', 'pt', 'Obra na via'),
    ('WEATHERHAZARD', 'HAZARD_ON_ROAD_CONSTRUCTION', 'en', 'Construction on road'),
    ('WEATHERHAZARD', 'HAZARD_ON_ROAD_CONSTRUCTION', 'es', 'Obras en la vía'),
    ('WEATHERHAZARD', 'HAZARD_ON_ROAD_ICE', 'pt', 'Gelo na pista'),
    ('WEATHERHAZARD', 'HAZARD_ON_ROAD_ICE', 'en', 'Ice on road'),
    ('WEATHERHAZARD', 'HAZARD_ON_ROAD_ICE', 'es', 'Hielo en la vía'),
    ('WEATHERHAZARD', 'HAZARD_ON_ROAD_LANE_CLOSED', 'pt', 'Faixa fechada'),
    ('WEATHERHAZARD', 'HAZARD_ON_ROAD_LANE_CLOSED', 'en', 'Lane closed'),
    ('WEATHERHAZARD', 'HAZARD_ON_ROAD_LANE_CLOSED', 'es', 'Carril cerrado'),
    ('WEATHERHAZARD', 'HAZARD_ON_ROAD_OBJECT', 'pt', 'Objeto na pista'),
    ('WEATHERHAZARD', 'HAZARD_ON_ROAD_OBJECT', 'en', 'Object on road'),
    ('WEATHERHAZARD', 'HAZARD_ON_ROAD_OBJECT', 'es', 'Objeto en la vía'),
    ('WEATHERHAZARD', 'HAZARD_ON_ROAD_OIL', 'pt', 'Óleo na pista'),
    ('WEATHERHAZARD', 'HAZARD_ON_ROAD_OIL', 'en', 'Oil on road'),
    ('WEATHERHAZARD', 'HAZARD_ON_ROAD_OIL', 'es', 'Aceite en la vía'),
    ('WEATHERHAZARD', 'HAZARD_ON_ROAD_POT_HOLE', 'pt', 'Buraco na pista'),
    ('WEATHERHAZARD', 'HAZARD_ON_ROAD_POT_HOLE', 'en', 'Pot hole'),
    ('WEATHERHAZARD', 'HAZARD_ON_ROAD_POT_HOLE', 'es', 'Bache en la vía'),
    ('WEATHERHAZARD', 'HAZARD_ON_ROAD_ROAD_KILL', 'pt', 'Animal morto na pista'),
    ('WEATHERHAZARD', 'HAZARD_ON_ROAD_ROAD_KILL', 'en', 'Road kill'),
    ('WEATHERHAZARD', 'HAZARD_ON_ROAD_ROAD_KILL', 'es', 'Animal atropellado en la vía'),
    ('WEATHERHAZARD', 'HAZARD_ON_ROAD_TRAFFIC_LIGHT_FAULT', 'pt', 'Semáforo com defeito'),
    ('WEATHERHAZARD', 'HAZARD_ON_ROAD_TRAFFIC_LIGHT_FAULT', 'en', 'Traffic light fault'),
    ('WEATHERHAZARD', 'HAZARD_ON_ROAD_TRAFFIC_LIGHT_FAULT', 'es', 'Semáforo averiado'),
    ('WEATHERHAZARD', 'HAZARD_ON_SHOULDER', 'pt', 'Perigo no acostamento'),
    ('WEATHERHAZARD', 'HAZARD_ON_SHOULDER', 'en', 'Hazard on shoulder'),
    ('WEATHERHAZARD', 'HAZARD_ON_SHOULDER', 'es', 'Peligro en el acotamiento'),
    ('WEATHERHAZARD', 'HAZARD_ON_SHOULDER_ANIMALS', 'pt', 'Animais no acostamento'),
    ('WEATHERHAZARD', 'HAZARD_ON_SHOULDER_ANIMALS', 'en', 'Animals on shoulder'),
    ('WEATHERHAZARD', 'HAZARD_ON_SHOULDER_ANIMALS', 'es', 'Animales en el acotamiento'),
    ('WEATHERHAZARD', 'HAZARD_ON_SHOULDER_CAR_STOPPED', 'pt', 'Veículo parado no acostamento'),
    ('WEATHERHAZARD', 'HAZARD_ON_SHOULDER_CAR_STOPPED', 'en', 'Car stopped on shoulder'),
    ('WEATHERHAZARD', 'HAZARD_ON_SHOULDER_CAR_STOPPED', 'es', 'Vehículo detenido en el acotamiento'),
    ('WEATHERHAZARD', 'HAZARD_ON_SHOULDER_MISSING_SIGN', 'pt', 'Placa de sinalização ausente'),
    ('WEATHERHAZARD', 'HAZARD_ON_SHOULDER_MISSING_SIGN', 'en', 'Missing sign'),
    ('WEATHERHAZARD', 'HAZARD_ON_SHOULDER_MISSING_SIGN', 'es', 'Señal de tránsito ausente'),
    ('WEATHERHAZARD', 'HAZARD_WEATHER', 'pt', 'Condição climática'),
    ('WEATHERHAZARD', 'HAZARD_WEATHER', 'en', 'Weather hazard'),
    ('WEATHERHAZARD', 'HAZARD_WEATHER', 'es', 'Peligro climático'),
    ('WEATHERHAZARD', 'HAZARD_WEATHER_FLOOD', 'pt', 'Alagamento'),
    ('WEATHERHAZARD', 'HAZARD_WEATHER_FLOOD', 'en', 'Flood'),
    ('WEATHERHAZARD', 'HAZARD_WEATHER_FLOOD', 'es', 'Inundación'),
    ('WEATHERHAZARD', 'HAZARD_WEATHER_FOG', 'pt', 'Neblina'),
    ('WEATHERHAZARD', 'HAZARD_WEATHER_FOG', 'en', 'Fog'),
    ('WEATHERHAZARD', 'HAZARD_WEATHER_FOG', 'es', 'Niebla'),
    ('WEATHERHAZARD', 'HAZARD_WEATHER_FREEZING_RAIN', 'pt', 'Chuva congelante'),
    ('WEATHERHAZARD', 'HAZARD_WEATHER_FREEZING_RAIN', 'en', 'Freezing rain'),
    ('WEATHERHAZARD', 'HAZARD_WEATHER_FREEZING_RAIN', 'es', 'Lluvia helada'),
    ('WEATHERHAZARD', 'HAZARD_WEATHER_HAIL', 'pt', 'Granizo'),
    ('WEATHERHAZARD', 'HAZARD_WEATHER_HAIL', 'en', 'Hail'),
    ('WEATHERHAZARD', 'HAZARD_WEATHER_HAIL', 'es', 'Granizo'),
    ('WEATHERHAZARD', 'HAZARD_WEATHER_HEAT_WAVE', 'pt', 'Onda de calor'),
    ('WEATHERHAZARD', 'HAZARD_WEATHER_HEAT_WAVE', 'en', 'Heat wave'),
    ('WEATHERHAZARD', 'HAZARD_WEATHER_HEAT_WAVE', 'es', 'Ola de calor'),
    ('WEATHERHAZARD', 'HAZARD_WEATHER_HEAVY_RAIN', 'pt', 'Chuva forte'),
    ('WEATHERHAZARD', 'HAZARD_WEATHER_HEAVY_RAIN', 'en', 'Heavy rain'),
    ('WEATHERHAZARD', 'HAZARD_WEATHER_HEAVY_RAIN', 'es', 'Lluvia fuerte'),
    ('WEATHERHAZARD', 'HAZARD_WEATHER_HEAVY_SNOW', 'pt', 'Neve intensa'),
    ('WEATHERHAZARD', 'HAZARD_WEATHER_HEAVY_SNOW', 'en', 'Heavy snow'),
    ('WEATHERHAZARD', 'HAZARD_WEATHER_HEAVY_SNOW', 'es', 'Nieve intensa'),
    ('WEATHERHAZARD', 'HAZARD_WEATHER_HURRICANE', 'pt', 'Furacão'),
    ('WEATHERHAZARD', 'HAZARD_WEATHER_HURRICANE', 'en', 'Hurricane'),
    ('WEATHERHAZARD', 'HAZARD_WEATHER_HURRICANE', 'es', 'Huracán'),
    ('WEATHERHAZARD', 'HAZARD_WEATHER_MONSOON', 'pt', 'Monção'),
    ('WEATHERHAZARD', 'HAZARD_WEATHER_MONSOON', 'en', 'Monsoon'),
    ('WEATHERHAZARD', 'HAZARD_WEATHER_MONSOON', 'es', 'Monzón'),
    ('WEATHERHAZARD', 'HAZARD_WEATHER_TORNADO', 'pt', 'Tornado'),
    ('WEATHERHAZARD', 'HAZARD_WEATHER_TORNADO', 'en', 'Tornado'),
    ('WEATHERHAZARD', 'HAZARD_WEATHER_TORNADO', 'es', 'Tornado'),
    ('WEATHERHAZARD', 'NO_SUBTYPE', 'pt', 'Sem subtipo específico'),
    ('WEATHERHAZARD', 'NO_SUBTYPE', 'en', 'No specific subtype'),
    ('WEATHERHAZARD', 'NO_SUBTYPE', 'es', 'Sin subtipo específico');
SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE waze_alert_type');
    }
}
