<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260912224450 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE waze_alerts (id INT AUTO_INCREMENT NOT NULL, uuid VARCHAR(36) NOT NULL, type VARCHAR(50) NOT NULL, subtype VARCHAR(100) DEFAULT NULL, pub_millis BIGINT NOT NULL, report_by_municipality_user TINYINT NOT NULL, report_rating SMALLINT NOT NULL, confidence SMALLINT NOT NULL, reliability SMALLINT NOT NULL, longitude NUMERIC(10, 7) NOT NULL, latitude NUMERIC(10, 7) NOT NULL, street VARCHAR(255) DEFAULT NULL, city VARCHAR(100) NOT NULL, country VARCHAR(2) NOT NULL, road_type SMALLINT NOT NULL, report_description LONGTEXT DEFAULT NULL, n_thumbs_up SMALLINT NOT NULL, magvar SMALLINT NOT NULL, collected_at DATETIME NOT NULL, UNIQUE INDEX uniq_uuid (uuid), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE waze_jams (id INT AUTO_INCREMENT NOT NULL, uuid VARCHAR(36) NOT NULL, jam_id BIGINT NOT NULL, line JSON DEFAULT NULL, line_points SMALLINT NOT NULL, speed NUMERIC(10, 3) NOT NULL, speed_kmh NUMERIC(10, 3) NOT NULL, length INT NOT NULL, delay INT NOT NULL, level SMALLINT NOT NULL, pub_millis BIGINT NOT NULL, turn_type VARCHAR(20) NOT NULL, blocking_alert_uuid VARCHAR(36) DEFAULT NULL, segments JSON DEFAULT NULL, segment_count SMALLINT NOT NULL, street VARCHAR(255) DEFAULT NULL, city VARCHAR(100) NOT NULL, country VARCHAR(2) NOT NULL, road_type SMALLINT NOT NULL, end_node VARCHAR(255) DEFAULT NULL, collected_at DATETIME NOT NULL, UNIQUE INDEX uniq_uuid (uuid), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('ALTER TABLE waze_alert DROP FOREIGN KEY `FK_741E86949393F8FE`');
        $this->addSql('ALTER TABLE waze_jam DROP FOREIGN KEY `FK_8CD6C02A9393F8FE`');
        $this->addSql('DROP TABLE waze_alert');
        $this->addSql('DROP TABLE waze_jam');
        $this->addSql('ALTER TABLE cemaden_hidro_observation CHANGE station_code station_code VARCHAR(50) DEFAULT NULL, CHANGE station_name station_name VARCHAR(255) DEFAULT NULL, CHANGE city city VARCHAR(100) DEFAULT NULL, CHANGE state state VARCHAR(2) DEFAULT NULL, CHANGE offset_value offset_value DOUBLE PRECISION DEFAULT NULL, CHANGE observed_at observed_at DATETIME DEFAULT NULL, CHANGE source_payload source_payload VARCHAR(50) DEFAULT NULL, CHANGE water_level water_level DOUBLE PRECISION DEFAULT NULL, CHANGE flow flow DOUBLE PRECISION DEFAULT NULL, CHANGE rain rain DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE cemaden_hidro_station_link CHANGE station_code station_code VARCHAR(100) DEFAULT NULL, CHANGE station_name station_name VARCHAR(255) DEFAULT NULL, CHANGE city city VARCHAR(150) DEFAULT NULL, CHANGE state state VARCHAR(2) DEFAULT NULL, CHANGE base_url base_url LONGTEXT NOT NULL, CHANGE last_fetched_at last_fetched_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE cemaden_pluviometric_observation CHANGE accumulated_rainfall accumulated_rainfall NUMERIC(8, 3) DEFAULT NULL, CHANGE source_payload source_payload JSON NOT NULL');
        $this->addSql('ALTER TABLE cemaden_station_link CHANGE station_code station_code VARCHAR(100) DEFAULT NULL, CHANGE station_name station_name VARCHAR(255) NOT NULL, CHANGE status status VARCHAR(30) DEFAULT NULL, CHANGE station_type station_type VARCHAR(100) DEFAULT NULL, CHANGE city city VARCHAR(150) DEFAULT NULL, CHANGE state state VARCHAR(2) DEFAULT NULL, CHANGE ibge_code ibge_code VARCHAR(20) DEFAULT NULL, CHANGE network_name network_name VARCHAR(255) DEFAULT NULL, CHANGE network_acronym network_acronym VARCHAR(50) DEFAULT NULL, CHANGE base_url base_url LONGTEXT NOT NULL, CHANGE last_fetched_at last_fetched_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE partner ADD api_secret VARCHAR(255) DEFAULT NULL, ADD fetch_frequency INT DEFAULT NULL, ADD fetch_frequency_unit VARCHAR(20) DEFAULT NULL, ADD last_fetch_at DATETIME DEFAULT NULL, CHANGE name name VARCHAR(255) NOT NULL, CHANGE code code VARCHAR(50) NOT NULL, CHANGE city city VARCHAR(255) DEFAULT NULL, CHANGE state state VARCHAR(2) DEFAULT NULL, CHANGE api_key api_key VARCHAR(255) DEFAULT NULL, CHANGE api_token api_token VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE partner_api_link CHANGE type type VARCHAR(20) NOT NULL, CHANGE name name VARCHAR(255) NOT NULL, CHANGE url url VARCHAR(2048) NOT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE partner_camera_link CHANGE name name VARCHAR(255) NOT NULL, CHANGE url url LONGTEXT NOT NULL, CHANGE url_type url_type VARCHAR(50) DEFAULT NULL, CHANGE city city VARCHAR(150) DEFAULT NULL, CHANGE state state VARCHAR(2) DEFAULT NULL, CHANGE country_code country_code VARCHAR(2) DEFAULT NULL, CHANGE provider provider VARCHAR(100) DEFAULT NULL, CHANGE metadata metadata JSON DEFAULT NULL, CHANGE notes notes LONGTEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE reset_password_request CHANGE selector selector VARCHAR(20) NOT NULL, CHANGE hashed_token hashed_token VARCHAR(100) NOT NULL');
        $this->addSql('ALTER TABLE user CHANGE email email VARCHAR(180) NOT NULL, CHANGE roles roles JSON NOT NULL, CHANGE password password VARCHAR(255) NOT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL, CHANGE phone phone VARCHAR(50) DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL, CHANGE last_login_at last_login_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE waze_tvt_irregularity CHANGE type type VARCHAR(255) DEFAULT NULL, CHANGE severity severity VARCHAR(255) DEFAULT NULL, CHANGE reported_time reported_time DATETIME DEFAULT NULL, CHANGE street street VARCHAR(255) DEFAULT NULL, CHANGE city city VARCHAR(255) DEFAULT NULL, CHANGE state state VARCHAR(2) DEFAULT NULL, CHANGE latitude latitude DOUBLE PRECISION DEFAULT NULL, CHANGE longitude longitude DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE waze_tvt_route_snapshot CHANGE name name VARCHAR(255) DEFAULT NULL, CHANGE city city VARCHAR(255) DEFAULT NULL, CHANGE state state VARCHAR(2) DEFAULT NULL');
        $this->addSql('ALTER TABLE waze_tvt_sub_route CHANGE name name VARCHAR(255) DEFAULT NULL, CHANGE city city VARCHAR(255) DEFAULT NULL, CHANGE state state VARCHAR(2) DEFAULT NULL');
        $this->addSql('ALTER TABLE waze_tvt_user_on_jam CHANGE username username VARCHAR(255) DEFAULT NULL, CHANGE jam_type jam_type VARCHAR(255) DEFAULT NULL, CHANGE street street VARCHAR(255) DEFAULT NULL, CHANGE city city VARCHAR(255) DEFAULT NULL, CHANGE state state VARCHAR(2) DEFAULT NULL');
        $this->addSql('ALTER TABLE weather_location CHANGE name name VARCHAR(150) NOT NULL, CHANGE city city VARCHAR(150) DEFAULT NULL, CHANGE state state VARCHAR(150) DEFAULT NULL, CHANGE country_code country_code VARCHAR(2) DEFAULT NULL, CHANGE timezone timezone VARCHAR(64) DEFAULT NULL, CHANGE provider provider VARCHAR(50) NOT NULL, CHANGE api_token api_token LONGTEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE weather_observation CHANGE temperature temperature NUMERIC(5, 2) DEFAULT NULL, CHANGE apparent_temperature apparent_temperature NUMERIC(5, 2) DEFAULT NULL, CHANGE precipitation precipitation NUMERIC(6, 2) DEFAULT NULL, CHANGE rain rain NUMERIC(6, 2) DEFAULT NULL, CHANGE showers showers NUMERIC(6, 2) DEFAULT NULL, CHANGE snowfall snowfall NUMERIC(6, 2) DEFAULT NULL, CHANGE surface_pressure surface_pressure NUMERIC(7, 2) DEFAULT NULL, CHANGE wind_speed wind_speed NUMERIC(6, 2) DEFAULT NULL, CHANGE wind_gusts wind_gusts NUMERIC(6, 2) DEFAULT NULL, CHANGE payload payload JSON NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE waze_alert (id INT AUTO_INCREMENT NOT NULL, alert_id VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, street LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_uca1400_ai_ci`, city VARCHAR(150) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, country VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, alert_type VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, alert_subtype VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, reliability SMALLINT DEFAULT NULL, report_description LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_uca1400_ai_ci`, report_rating SMALLINT DEFAULT NULL, confidence SMALLINT DEFAULT NULL, pub_millis BIGINT NOT NULL, pub_utc_date DATETIME NOT NULL, location_latitude NUMERIC(10, 7) NOT NULL, location_longitude NUMERIC(10, 7) NOT NULL, magvar NUMERIC(10, 7) DEFAULT \'NULL\', num_thumbs_up SMALLINT DEFAULT NULL, num_comments SMALLINT DEFAULT NULL, report_by VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, source_payload LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_bin`, is_active INT DEFAULT 1 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, partner_id INT NOT NULL, UNIQUE INDEX UNIQ_741E869493035F72 (alert_id), INDEX IDX_741E86949393F8FE (partner_id), INDEX IDX_741E86949393F8FE85E2D6C3 (partner_id, pub_millis), PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE waze_jam (id INT AUTO_INCREMENT NOT NULL, jam_id VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, street LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_uca1400_ai_ci`, city VARCHAR(150) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, country VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, level SMALLINT DEFAULT NULL, delay INT DEFAULT NULL, length INT DEFAULT NULL, turn_type VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, type VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, pub_millis BIGINT NOT NULL, pub_utc_date DATETIME NOT NULL, start_location_latitude NUMERIC(10, 7) NOT NULL, start_location_longitude NUMERIC(10, 7) NOT NULL, end_location_latitude NUMERIC(10, 7) NOT NULL, end_location_longitude NUMERIC(10, 7) NOT NULL, line LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_bin`, source_payload LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_bin`, is_active INT DEFAULT 1 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, partner_id INT NOT NULL, INDEX IDX_8CD6C02A9393F8FE85E2D6C3 (partner_id, pub_millis), UNIQUE INDEX UNIQ_8CD6C02AECB3E09E (jam_id), INDEX IDX_8CD6C02A9393F8FE (partner_id), PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE waze_alert ADD CONSTRAINT `FK_741E86949393F8FE` FOREIGN KEY (partner_id) REFERENCES partner (id)');
        $this->addSql('ALTER TABLE waze_jam ADD CONSTRAINT `FK_8CD6C02A9393F8FE` FOREIGN KEY (partner_id) REFERENCES partner (id)');
        $this->addSql('DROP TABLE waze_alerts');
        $this->addSql('DROP TABLE waze_jams');
        $this->addSql('ALTER TABLE cemaden_hidro_observation CHANGE station_code station_code VARCHAR(50) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE station_name station_name VARCHAR(255) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE city city VARCHAR(100) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE state state VARCHAR(2) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE offset_value offset_value DOUBLE PRECISION DEFAULT \'NULL\', CHANGE observed_at observed_at DATETIME DEFAULT \'NULL\', CHANGE source_payload source_payload VARCHAR(50) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE water_level water_level DOUBLE PRECISION DEFAULT \'NULL\', CHANGE flow flow DOUBLE PRECISION DEFAULT \'NULL\', CHANGE rain rain DOUBLE PRECISION DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE cemaden_hidro_station_link CHANGE station_code station_code VARCHAR(100) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE station_name station_name VARCHAR(255) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE city city VARCHAR(150) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE state state VARCHAR(2) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE base_url base_url LONGTEXT NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE last_fetched_at last_fetched_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE cemaden_pluviometric_observation CHANGE accumulated_rainfall accumulated_rainfall NUMERIC(8, 3) DEFAULT \'NULL\', CHANGE source_payload source_payload LONGTEXT NOT NULL COLLATE `utf8mb4_bin`');
        $this->addSql('ALTER TABLE cemaden_station_link CHANGE station_code station_code VARCHAR(100) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE station_name station_name VARCHAR(255) NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE status status VARCHAR(30) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE station_type station_type VARCHAR(100) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE city city VARCHAR(150) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE state state VARCHAR(2) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE ibge_code ibge_code VARCHAR(20) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE network_name network_name VARCHAR(255) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE network_acronym network_acronym VARCHAR(50) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE base_url base_url LONGTEXT NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE last_fetched_at last_fetched_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE partner DROP api_secret, DROP fetch_frequency, DROP fetch_frequency_unit, DROP last_fetch_at, CHANGE name name VARCHAR(255) NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE code code VARCHAR(50) NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE city city VARCHAR(255) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE state state VARCHAR(2) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE api_key api_key VARCHAR(255) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE api_token api_token VARCHAR(255) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`');
        $this->addSql('ALTER TABLE partner_api_link CHANGE type type VARCHAR(20) NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE name name VARCHAR(255) NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE url url VARCHAR(2048) NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE partner_camera_link CHANGE name name VARCHAR(255) NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE url url LONGTEXT NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE url_type url_type VARCHAR(50) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE city city VARCHAR(150) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE state state VARCHAR(2) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE country_code country_code VARCHAR(2) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE provider provider VARCHAR(100) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE metadata metadata LONGTEXT DEFAULT NULL COLLATE `utf8mb4_bin`, CHANGE notes notes LONGTEXT DEFAULT NULL COLLATE `utf8mb4_uca1400_ai_ci`');
        $this->addSql('ALTER TABLE reset_password_request CHANGE selector selector VARCHAR(20) NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE hashed_token hashed_token VARCHAR(100) NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`');
        $this->addSql('ALTER TABLE user CHANGE email email VARCHAR(180) NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE roles roles LONGTEXT NOT NULL COLLATE `utf8mb4_bin`, CHANGE password password VARCHAR(255) NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE name name VARCHAR(255) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE phone phone VARCHAR(50) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE created_at created_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\', CHANGE last_login_at last_login_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE waze_tvt_irregularity CHANGE type type VARCHAR(255) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE severity severity VARCHAR(255) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE reported_time reported_time DATETIME DEFAULT \'NULL\', CHANGE street street VARCHAR(255) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE city city VARCHAR(255) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE state state VARCHAR(2) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE latitude latitude DOUBLE PRECISION DEFAULT \'NULL\', CHANGE longitude longitude DOUBLE PRECISION DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE waze_tvt_route_snapshot CHANGE name name VARCHAR(255) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE city city VARCHAR(255) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE state state VARCHAR(2) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`');
        $this->addSql('ALTER TABLE waze_tvt_sub_route CHANGE name name VARCHAR(255) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE city city VARCHAR(255) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE state state VARCHAR(2) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`');
        $this->addSql('ALTER TABLE waze_tvt_user_on_jam CHANGE username username VARCHAR(255) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE jam_type jam_type VARCHAR(255) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE street street VARCHAR(255) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE city city VARCHAR(255) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE state state VARCHAR(2) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`');
        $this->addSql('ALTER TABLE weather_location CHANGE name name VARCHAR(150) NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE city city VARCHAR(150) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE state state VARCHAR(150) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE country_code country_code VARCHAR(2) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE timezone timezone VARCHAR(64) DEFAULT \'NULL\' COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE provider provider VARCHAR(50) NOT NULL COLLATE `utf8mb4_uca1400_ai_ci`, CHANGE api_token api_token LONGTEXT DEFAULT NULL COLLATE `utf8mb4_uca1400_ai_ci`');
        $this->addSql('ALTER TABLE weather_observation CHANGE temperature temperature NUMERIC(5, 2) DEFAULT \'NULL\', CHANGE apparent_temperature apparent_temperature NUMERIC(5, 2) DEFAULT \'NULL\', CHANGE precipitation precipitation NUMERIC(6, 2) DEFAULT \'NULL\', CHANGE rain rain NUMERIC(6, 2) DEFAULT \'NULL\', CHANGE showers showers NUMERIC(6, 2) DEFAULT \'NULL\', CHANGE snowfall snowfall NUMERIC(6, 2) DEFAULT \'NULL\', CHANGE surface_pressure surface_pressure NUMERIC(7, 2) DEFAULT \'NULL\', CHANGE wind_speed wind_speed NUMERIC(6, 2) DEFAULT \'NULL\', CHANGE wind_gusts wind_gusts NUMERIC(6, 2) DEFAULT \'NULL\', CHANGE payload payload LONGTEXT NOT NULL COLLATE `utf8mb4_bin`');
    }
}
