parameters:
    partner_feeds_save_raw: '%env(bool:PARTNER_FEEDS_SAVE_RAW)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\\Service\\PartnerFeedRawStorage:
        arguments:
            $projectDir: '%kernel.project_dir%'
            $enabled: '%partner_feeds_save_raw%'
