[program:waze_scheduler_dev]
command=php /var/www/wazeBR-symfony/bin/console messenger:consume scheduler_waze_feed --time-limit=3600 --memory-limit=64M
directory=/var/www/wazeBR-symfony
autostart=true
autorestart=true
startretries=3
stopwaitsecs=30
user=www-data
stdout_logfile=/var/log/supervisor/waze_scheduler_dev.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=3
stderr_logfile=/var/log/supervisor/waze_scheduler_dev_error.log
redirect_stderr=false
environment=APP_ENV="dev",APP_DEBUG="1"
