[program:waze_scheduler]
command=php /var/www/wazeBR-symfony/bin/console messenger:consume scheduler_waze_feed --time-limit=3600 --memory-limit=128M
directory=/var/www/wazeBR-symfony
autostart=true
autorestart=true
startretries=5
stopwaitsecs=60
user=www-data
stdout_logfile=/var/log/supervisor/waze_scheduler.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
stderr_logfile=/var/log/supervisor/waze_scheduler_error.log
redirect_stderr=false
environment=APP_ENV="prod",APP_DEBUG="0"
